services:
  - type: worker
    name: render-subnet-router
    env: docker
    autoDeploy: false
    envVars:
      - key: TAILSCALE_AUTHKEY
        sync: false
      - key: TAILSCALE_VERSION
        value: 1.88.3
      - key: ADVERTISE_ROUTES
        value: 10.0.0.0/8
